// Nubo OS Server: install security updates automatically, reboot only on request.
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Origins-Pattern {
        "origin=Ubuntu,codename=${distro_codename}-security";
        "origin=Ubuntu,codename=${distro_codename}-updates";
        "origin=Nubo,codename=${distro_codename}";
};
