#!/bin/sh
set -e

DIVERTED="/usr/lib/os-release
/etc/issue
/etc/lsb-release
/etc/issue.net
/usr/share/applications/gnome-ubuntu-panel.desktop
/usr/share/applications/org.gnome.Software.desktop
/etc/legal
/usr/share/pixmaps/ubuntu-logo.svg
/usr/share/pixmaps/ubuntu-logo-text.svg
/usr/share/pixmaps/ubuntu-logo-text.png
/usr/share/pixmaps/ubuntu-logo-text-dark.svg
/usr/share/pixmaps/ubuntu-logo-text-dark.png"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /etc/issue /etc/issue.net /etc/lsb-release
    for file in $DIVERTED; do
        dpkg-divert --package nubo-branding --remove --rename \
            --divert "$file.ubuntu" "$file"
    done
    dpkg-divert --package nubo-branding --remove --rename \
        --divert /usr/share/nubo/os/grub-10_linux.ubuntu /etc/grub.d/10_linux
    dpkg-divert --package nubo-branding --remove --rename \
        --divert /usr/share/wayland-sessions/ubuntu.desktop.ubuntu /usr/share/wayland-sessions/ubuntu.desktop
    update-alternatives --remove text.plymouth /usr/share/plymouth/themes/nubo-text/nubo-text.plymouth || true
    if command -v update-grub >/dev/null 2>&1; then
        update-grub || true
    fi
fi

#DEBHELPER#
