#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = purge ]; then
    for unit in motd-news.timer motd-news.service whoopsie.service whoopsie.path \
                apport.service apport-autoreport.path apport-autoreport.timer apport-autoreport.service \
                ua-timer.timer ua-timer.service apt-news.service esm-cache.service \
                ubuntu-advantage.service ubuntu-advantage-desktop-daemon.service; do
        [ "$(readlink "/etc/systemd/system/$unit" 2>/dev/null)" = /dev/null ] && rm -f "/etc/systemd/system/$unit"
    done
    for file in /etc/chrony/sources.d/ubuntu-ntp-pools.sources /etc/debuginfod/elfutils.urls /etc/update-manager/release-upgrades; do
        rm -f "$file"
        dpkg-divert --package nubo-base --quiet --remove --rename "$file" || true
    done
fi
#DEBHELPER#
