account/nubo-account-setup usr/libexec/nubo/
account/nubo-account-setup.service usr/lib/systemd/system/
account/brokers.d/nubo.conf etc/authd/brokers.d/
build/account/nubo-account.png usr/share/nubo/logo/
account/nubo-setup usr/libexec/nubo/
account/tech.nubosuite.Setup.desktop usr/share/applications/
build/account/tech.nubosuite.Setup.svg usr/share/icons/hicolor/scalable/apps/
account/nubo-setup-autostart.desktop etc/xdg/autostart/
