#!/usr/bin/env bash
# Build the installer's white-label files: page illustrations, slides and the
# configuration that ties them together.
#
# The installer reads /usr/share/desktop-provision/whitelabel.yaml and takes
# page images from /usr/share/desktop-provision/images/ and slides from
# /usr/share/desktop-provision/slides/N/. Illustrations are built from GNOME's
# symbolic icons and the Nubo mark, so they match the desktop's own icons.
#
# Usage: make-installer-branding.sh OUTPUT_DIR LOGO_DIR
# Needs adwaita-icon-theme installed.

set -euo pipefail

OUT="${1:?output directory required}"
LOGOS="${2:?logo directory required}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ADWAITA="${ADWAITA:-/usr/share/icons/Adwaita/symbolic}"

rm -rf "${OUT}"
mkdir -p "${OUT}/images" "${OUT}/slides"

# page:icon. "mark" means the Nubo logo itself.
PAGES=(
  locale:mark
  accessibility:preferences-desktop-accessibility
  try-or-install:mark
  rst:drive-harddisk
  keyboard:input-keyboard
  network:network-wireless
  refresh:view-refresh
  autoinstall:system-run
  autoinstall-direct:system-run
  autoinstall-landscape-domain:network-server
  autoinstall-landscape-error:dialog-error
  source-selection:view-app-grid
  codecs-and-drivers:application-x-addon
  not-enough-disk-space:drive-harddisk
  secure-boot:channel-secure
  bitlocker:drive-harddisk
  storage:drive-harddisk
  guided-capabilities:channel-secure
  tpm-action:channel-secure
  guided-resize:drive-harddisk
  guided-reformat:drive-harddisk
  passphrase-type:dialog-password
  passphrase:dialog-password
  recovery-key:dialog-password
  confirm:object-select
  identity:avatar-default
  active-directory:network-server
  telemetry:computer
  done:mark
  storage-icon:mark
  error:dialog-error
)

# Wrap a 16x16 symbolic icon into a 380x380 illustration. One mid-grey
# colour is used for everything: the installer does not reliably switch to
# the dark variant, and mid-grey reads on both its light and dark windows.
INK="#8c8c8c"

icon_svg() {
  local name="$1" out="$2"
  local src
  src="$(find "${ADWAITA}" -name "${name}-symbolic.svg" | head -1)"
  [[ -n "${src}" ]] || { echo "icon not found: ${name}" >&2; exit 1; }
  local inner
  inner="$(sed -e '1,/<svg[^>]*>/d' -e '/<\/svg>/,$d' "${src}")"
  cat >"${out}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="380" height="380" viewBox="0 0 16 16">
  <g fill="${INK}" transform="translate(4 4) scale(0.5)">
${inner}
  </g>
</svg>
EOF
}

mark_svg() {
  local out="$1"
  sed -e "s/fill=\"#ffffff\"/fill=\"${INK}\"/" "${LOGOS}/nubo-mark-white.svg" >"${out}"
}

{
  echo "# Nubo OS installer appearance. Generated by make-installer-branding.sh."
  echo "app-name: Nubo OS installer"
  echo "theme:"
  echo "  light:"
  echo "    accent-color: '#2b2b2b'"
  echo "    elevated-button-color: '#111111'"
  echo "    elevated-button-text-color: '#ffffff'"
  echo "  dark:"
  echo "    accent-color: '#e6e6e6'"
  echo "    elevated-button-color: '#f2f2f2'"
  echo "    elevated-button-text-color: '#0a0a0a'"
  echo "pages:"
  for entry in "${PAGES[@]}"; do
    page="${entry%%:*}"
    icon="${entry##*:}"
    # Pictures are PNG: the installer's SVG renderer drops or shrinks these
    # drawings (they came out as dots). An earlier hang blamed on PNG was
    # really the first-boot cleanup running on the media.
    if [[ "${icon}" == mark ]]; then
      mark_svg "${OUT}/images/${page}.svg"
    else
      icon_svg "${icon}" "${OUT}/images/${page}.svg"
    fi
    rsvg-convert -w 760 -h 760 -a "${OUT}/images/${page}.svg" -o "${OUT}/images/${page}.png"
    # Dark-mode copy with lighter ink, so the picture does not sink into the window.
    sed "s/${INK}/#d9d9d9/g" "${OUT}/images/${page}.svg" >"${OUT}/images/${page}-dark.svg"
    rsvg-convert -w 760 -h 760 -a "${OUT}/images/${page}-dark.svg" -o "${OUT}/images/${page}-dark.png"
    rm -f "${OUT}/images/${page}.svg" "${OUT}/images/${page}-dark.svg"
    # Both keys, same file: the built-in defaults set a dark variant for some
    # pages, and a dark variant wins over a light one in dark mode.
    echo "  ${page}:"
    echo "    image: \"${page}.png\""
    echo "    image-dark: \"${page}-dark.png\""
  done
  # Commercial pages that do not apply to Nubo OS.
  echo "  ubuntu-pro-onboarding:"
  echo "    visible: false"
} >"${OUT}/whitelabel.yaml"

# Slides shown while files copy. Each slide is one folder with the page and
# its pictures; a picture named x.svg gets x-dark.svg in dark mode.
slide() {
  local n="$1" title="$2" body="$3" icon="$4"
  local dir="${OUT}/slides/${n}"
  mkdir -p "${dir}"
  if [[ "${icon}" == mark ]]; then
    mark_svg "${dir}/picture.svg"
  else
    icon_svg "${icon}" "${dir}/picture.svg"
  fi
  sed -e "s|@TITLE@|${title}|" -e "s|@BODY@|${body}|" "${HERE}/slide-template.html" \
    >"${dir}/slide_en_US.html"
}

slide 1 "Welcome to Nubo OS" \
  "<p>A calm, focused desktop built for work.</p><p>Everything you need is a few clicks away, and nothing gets in your way.</p>" mark
slide 2 "One account, every app" \
  "<p>Sign in once with your Nubo account.</p><p>Mail, chat, files and passwords are ready when you are, on this machine and on your phone.</p>" avatar-default
slide 3 "Private by design" \
  "<p>Your data stays yours.</p><p>Nubo apps talk to each other directly and encrypted, and nothing is sent anywhere without your say.</p>" channel-secure
slide 4 "Familiar tools" \
  "<p>Browse the web, write documents, edit photos and manage your day with well-known open-source apps.</p><p>Thousands more are one search away in the app store.</p>" view-app-grid
slide 5 "Built on solid ground" \
  "<p>Nubo OS runs on Ubuntu long-term support, so security updates arrive for years.</p><p>Updates install in the background and never interrupt your work.</p>" system-run
slide 6 "Help when you need it" \
  "<p>Stuck? Open Help from the app grid, or reach the Nubo team from any Nubo app.</p><p>Thanks for choosing Nubo OS.</p>" computer

echo "installer branding: $(ls "${OUT}/images" | wc -l) images, $(ls "${OUT}/slides" | wc -l) slides"
